### ISSUE TITLE
Not an issue, just a way to reach out to you

### ISSUE THREAD

**Issue by rishabmehta7** [finity69x2/Home-Assistant#4]
HI!

I have all my devices using one of your button style thing (switches, lights, fans etc). Do you have any plan for a climate control buttons?
Would really appreciate as it would make all my stuff look uniform.

Rishab

**Comment by finity69x2** [comment]
Hey, I'm not even sure if you are still out there somewhere but I never look at this repo since it wasn't really meant for me to receive issues.

If you are still interested in this then can you PM on the HA forum?
